[package]
name = "krill-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
handlebars = "6.1.0"
reqwest = { version = "0.12.8", features = ["blocking"] }

[[bin]]
name = "krill"
path = "src/main.rs"
